<a href="https://colab.research.google.com/github/sharatainapur/Machine_Learning/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [ ]:
#Converting a list to array
a = np.array([1,3,4,6,7,1])

In [ ]:
a[2] = 10

In [ ]:
a

array([ 1,  3, 10,  6,  7,  1])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [ ]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

### Multi-dimensional array

In [ ]:
np.zeros((5,2)) # 5 rows and 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
two_dim = np.array([
    [1,2,3],
    [4,5,6]
    ])

In [ ]:
two_dim[0,0] = 20 

In [ ]:
two_dim

array([[20,  2,  3],
       [ 4,  5,  6]])

In [ ]:
two_dim[0,:]

array([20,  2,  3])

In [ ]:
two_dim[1]

array([4, 5, 6])

In [ ]:
two_dim[:,1]

array([2, 5])

In [ ]:
two_dim[:,2]=[0,0]
two_dim

array([[20,  2,  0],
       [ 4,  5,  0]])

## Randomly generated array

In [ ]:
np.random.seed(2)
# uniform distribution
np.random.rand(5,2)

## same seed - produces the same output.

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
# normal distribution
np.random.randn(5,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [ ]:
np.random.randint(low=10, high=100, size=(5,2))

array([[93, 41],
       [76, 90],
       [62, 86],
       [60, 14],
       [73, 89]])

## Element-wise operation

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 80

array([80, 81, 82, 83, 84])

In [ ]:
a * 5

array([ 0,  5, 10, 15, 20])

In [ ]:
## Chaining of operators
10 + ( a * 2)

array([10, 12, 14, 16, 18])

In [ ]:
b = np.arange(5)
b
a

array([0, 1, 2, 3, 4])

In [ ]:
a + b

array([0, 2, 4, 6, 8])

## Comparison Operations

In [ ]:
a >= 2

array([False, False,  True,  True,  True])

In [ ]:
a[a>2]


array([3, 4])

## Summarizing Operations

In [ ]:
 a.min()

0

In [ ]:
a.max()

4

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.0

In [ ]:
a.std()

1.4142135623730951

In [ ]:
two_dim.std()

6.890008869531462